# Generated by Django 5.0.1 on 2024-01-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GWP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='gamegenre',
            name='nombre',
        ),
    ]
