# Generated by Django 5.0.1 on 2024-01-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWP', '0003_alter_gamegenre_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamebygenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWP.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWP.gamegenre')),
            ],
        ),
    ]
