# Generated by Django 5.0.1 on 2024-02-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWP', '0004_gamebygenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='descripcion',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='game',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
