# Generated by Django 5.0.1 on 2024-02-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWP', '0005_game_descripcion_game_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='descripcion',
            field=models.TextField(blank=True, max_length=9999, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='game',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='gamebygenre',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWP.game', verbose_name='Juego'),
        ),
        migrations.AlterField(
            model_name='gamebygenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWP.gamegenre', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Género'),
        ),
    ]
